python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part1.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part1_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part2.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part2_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part3.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part3_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part4.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part4_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part5.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part5_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part6.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part6_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024H.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024H_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024I_part1.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024I_part1_*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024I_part2.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024I_part2_*.root
#
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part2_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part3.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part3_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part4.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part4_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part5.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part5_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part6.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part6_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024H.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024H_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024I_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024I_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024I_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024I_part2_*.root
#
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part2_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part3.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part3_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part4.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part4_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part5.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part5_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part6.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part6_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024H.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024H_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024I_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024I_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024I_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024I_part2_*.root
##
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_1000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_1500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_2000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_2500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6000/KBMTFsim_hwK/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6250/KBMTFsim_HLT/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6250/KBMTFsim_HLT/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6500/KBMTFsim_HLT/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6500/KBMTFsim_HLT/KB*.root

#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_1000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_1500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_2000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_2500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_3000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_3500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_4000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_4500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_5000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_5000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_5500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_5500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_6000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_6000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_6250/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_6250/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_6500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/GluinoBall_6500/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_4000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_4500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_5000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_5000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_5500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_5500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_6000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p0_6000/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_4000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_4500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_5000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_5000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_5500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p1_5500/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_4000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_4500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_5000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p2_5000/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_4000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_4500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_5000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p3_5000/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_4000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_4500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_5000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p4_5000/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_4000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p5_4500/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_4000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_4500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p6_4500/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_3000/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_3500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p7_4000/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p8_4000/KBMTFsim_hwK/KB*.root
##
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_1500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio2p9_4000/KBMTFsim_hwK/KB*.root

##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_1000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_1000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_1500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_1500/KBMTFsim_hwK/KB*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_2000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_2000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_2500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_2500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_3000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_3000/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_3500/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_3500/KBMTFsim_hwK/KB*.root
##python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_4000/KBMTFsim_hwK/total.root /eos/cms/store/group/cmst3/group/slowmuons/ZPrimeTo2TauPrime_ratio3p0_4000/KBMTFsim_hwK/KB*.root
##
