#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part1.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part2.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part2_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part3.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part3_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part4.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part4_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part5.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part5_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024G_part6.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024G_part6_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024H.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024H_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024I_part1.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024I_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/Scouting_2024I_part2.root /eos/cms/store/group/cmst3/group/slowmuons/Cleaned_SlowSkims/output_output_Scouting_2024I_part2_*.root

#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part2_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part3.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part3_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part4.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part4_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part5.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part5_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024G_part6.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024G_part6_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024H.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024H_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024I_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024I_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/Scouting_2024I_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuSkims/output_Scouting_2024I_part2_*.root
#
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part2_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part3.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part3_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part4.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part4_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part5.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part5_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024G_part6.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024G_part6_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024H.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024H_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024I_part1.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024I_part1_*.root
#python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/Scouting_2024I_part2.root /eos/cms/store/group/cmst3/group/slowmuons/ZmumuKBMTFSkims/output_Scouting_2024I_part2_*.root

python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_2600/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_2600/KBMTFsim/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3000/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3000/KBMTFsim/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3500/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_3500/KBMTFsim/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4000/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4000/KBMTFsim/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4500/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_4500/KBMTFsim/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5000/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5000/KBMTFsim/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5500/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_5500/KBMTFsim/KB*.root
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6000/KBMTFsim/total.root /eos/cms/store/group/cmst3/group/slowmuons/HSCPtauPrime_6000/KBMTFsim/KB*.root
