python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_0
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_1
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_2
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_3
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_4
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_5
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_6
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_7
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_8
python3 FinalSelection_ZmumuKBMTF.py  Scouting_2024H_9
python3 $CMSSW_BASE/src/PhysicsTools/NanoAOD/scripts/haddnano.py ZmumuKBMTF_Scouting_2024H.root ZmumuKBMTF_Scouting_2024H_*.root
python3 FinalSelection_ZmumuKBMTF.py  DY
