   unsigned int          run;
   unsigned int          luminosityBlock;
   unsigned int          bunchCrossing;
   unsigned int          orbitNumber;
   Double_t        mmumu;
   Bool_t          isOS;
   Double_t        DRmumu;
   Double_t        xsweight;
   Float_t         met;
   int           bxspread1;
   int           bxspread2;
   Bool_t          isL1MuMatched1;
   Bool_t          isL1MuMatched2;
   int           nstub1;
   int           nstub2;
   Double_t        pt1;
   Double_t        eta1;
   Double_t        phi1;
   int         charge1;
   int         qual1;
   int         dxy1;
   short         charge1_short;
   short         qual1_short;
   short         dxy1_short;
   Double_t        pt2;
   Double_t        eta2;
   Double_t        phi2;
   int         charge2;
   int         qual2;
   int         dxy2;
   short         charge2_short;
   short         qual2_short;
   short         dxy2_short;

